# Generated by Django 2.2 on 2023-07-10 13:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230710_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
