# Generated by Django 2.2 on 2023-07-10 13:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230710_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
