# Generated by Django 2.2 on 2023-07-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230710_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='encode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
