# Generated by Django 2.2 on 2023-07-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orderitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
